version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: issue-tracker-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-issue_tracker}
      MYSQL_USER: ${MYSQL_USER:-issueuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-issuepassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
      - ./db-setup.sql:/docker-entrypoint-initdb.d/db-setup.sql
    networks:
      - server-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  issue-tracker-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: issue-tracker-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER:-issueuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-issuepassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-issue_tracker}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - server-network-dev
    command: npm run dev

volumes:
  mysql-data-dev:
    driver: local

networks:
  server-network-dev:
    driver: bridge
