version: '3'

services:
  issue-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=^#0nNBvqSX^6m4w$96J4
      - MYSQL_DATABASE=issue_tracker
    networks:
      - server-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ^#0nNBvqSX^6m4w$96J4
      MYSQL_DATABASE: issue_tracker
    ports:
      - "33066:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - server-network

networks:
  server-network:
    external: true

volumes:
  mysql-data:

