FROM node:20-alpine

WORKDIR /app

# Install dependencies required for development
RUN apk add --no-cache libc6-compat

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Set environment variables
ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1

# Expose the port
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "dev"]
